### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-medical#198]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] medical - By @rgarnau - #200 
- [ ] medical_agpl
- [ ] medical_center - By @rgarnau - #201 
- [ ] medical_disease
- [ ] medical_insurance - By @rgarnau - #205 
- [ ] medical_insurance_us
- [ ] medical_medicament
- [ ] medical_medicament_attributes
- [ ] medical_medication
- [ ] medical_medication_us
- [ ] medical_patient_occupation
- [ ] medical_pharmacy
- [ ] medical_pharmacy_us
- [ ] medical_practitioner - By @rgarnau - #202 
- [ ] medical_prescription
- [ ] medical_prescription_sale
- [ ] medical_prescription_state
- [ ] medical_prescription_thread

**Comment by JordiBForgeFlow** [comment]
@lasley We have been brainstorming on how to best implement FHIR and decided that it's best for us to jump to 11.0 directly, and do some refactoring. We have decided that it's best for our team to work on an 11-dev branch https://github.com/Eficent/vertical-medical/tree/11.0-dev for now, until we can see that the concept is good. Then we'll start sending PR's to OCA.

**Comment by lasley** [comment]
Sounds like a good plan @jbeficent, thanks for dropping a line. 

We're still tidying up some things for v10, then will begin trying to figure out some sort of upgrade strategy.
